name: BluestarCraft
version: '${project.version}'
main: me.lanzhi.bluestarcraft.BluestarCraftPlugin
api-version: 1.13
commands:
  bluestarcraft:
    permission: BluestarCraft.command
    aliases:
      - bscraft
  opencraft:
    permission: BluestarCraft.opencraft
  recipesbook:
    permission: BluestarCraft.recipesbook
    aliases:
      - recipes
      - recipebook
permissions:
  BluestarCraft.*:
    children:
      BluestarCraft.recipesbook:
        default: true
      BluestarCraft.command:
        default: op
      BluestarCraft.opencraft:
        default: op
depend:
  - BluestarAPI