shaped:
  recipe1:
    shape:
      - '  a'
      - ' aaa'
      - 'aaaaa'
      - ' aaa'
      - '  a'
    result: 'diamond_block'
    amount: 2
    ingredients:
      a: 'diamond'
shapeless:
  recipe2:
    ingredients:
      diamond: 20
    result: 'diamond_block'
    amount: 5